export const TEST_DATA_START = "TEST_DATA_START";
export const TEST_DATA_SUCCESS = "TEST_DATA_SUCCESS";
export const TEST_DATA_FAILURE = "TEST_DATA_FAILURE";


export const STORES_DATA_START = "STORES_DATA_START";
export const STORES_DATA_SUCCESS = "STORES_DATA_SUCCESS";
export const STORES_DATA_FAILURE = "STORES_DATA_FAILURE";